# 系统配置
system:
  # 接口固定前缀
  api-prefix: /api
  # 接口版本
  api-version: v1

# 日志配置
log:
  # 是否打印日志到文件
  enabled: true
  # 日志等级，参考 zapcore.Level（-1<=level<=5，-1 / DEBUG）
  level: -1
  # 日志保存目录
  path: logs
  # 日志切割配置，单位 M
  max-size: 100
  # 日志保留天数
  max-age: 7
  # 日志保留个数
  max-backups: 10
  # 是否压缩
  compress: false

# 数据库日志配置
sql-log:
  # 是否打印数据库 SQL 日志
  enabled: true

# 数据库配置
mysql:
  # 主机地址
  host: 127.0.0.1
  # 端口
  port: 3306
  # 数据库
  database: change
  # 用户名
  username: root
  # 密码
  password: 123456
  # 字符集
  charset: utf8mb4
  # 排序规则
  collation: utf8mb4_bin
  # 超时时间，单位毫秒
  timeout: 1000
  # 额外参数
  extra-param: parseTime=True&loc=Local
  # 最大打开链接数
  max-open-conns: 100
  # 最大空闲连接数
  max-idle-conns: 10
  # 空闲连接最大超时时间，单位分钟
  max-idle-time: 30

# redis 配置
redis:
  # 主机地址
  host: 127.0.0.1
  # 端口
  port: 6379
  # 数据库
  database: 0
  # 密码，没有就不设置
  password: ""
  # 连接超时时间，单位秒
  timeout: 5
  # 最大连接数，一般比 CPU 核数 4 倍少一点
  max-open-conns: 12
  # 最小空闲连接
  min-idle-conns: 5
  # 最大空闲连接
  max-idle-conns: 10
  # 最大空闲时长，单位分钟
  max-idle-time: 10

# JWT 认证
jwt:
  # 领域，用于区分不同的认证范围
  realm: change
  # 用于签名和验证 JWT 令牌的密钥
  # 一般是一个随机生成的字符串，在中间件生成 JWT 令牌时，会使用这个密钥对令牌进行签名
  key: SNDAhUH8SCB7h06f72H8
  # Token 超时时间，单位秒，默认 1 天，Redis 中有效期也是如此
  timeout: 86400

# 登录配置
login:
  # 密码复杂度，支持 1-4
  password-level: 1
  # 密码错误上限，达到上限锁定账户
  wrong-times: 5
  # 账户锁定时间，单位秒，默认 5 分钟
  lock-time: 300
  # 是否允许多设备登录
  multi-devices: false
  # 重置密码 Token 过期时间
  reset-token-time: 300
